/* empty css                      */import{a as E,S as P,i}from"./assets/vendor-CIF6YjI2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const B="56203683-dd16d7902fd33711f42dee53b",H="https://pixabay.com/api/";let T="";const x=15;async function g(t,e){t!==T&&(e=1);try{return(await E.get(H,{params:{key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:x}})).data}catch(s){throw console.error("Error",s),s}}const O=new P(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");function L(t){f();const e=t.map(({webformatURL:s,largeImageURL:l,tags:r,likes:o,views:n,comments:M,downloads:$})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${s}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${o}</p>
            <p class="info-item"><b>Views</b> ${n}</p>
            <p class="info-item"><b>Comments</b> ${M}</p>
            <p class="info-item"><b>Downloads</b> ${$}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",e),O.refresh()}function f(){h.innerHTML=""}function b(){d&&d.classList.remove("is-hidden")}function w(){d?d.classList.add("is-hidden"):console.warn("Element is apsent")}function S(){u&&u.classList.remove("is-hidden")}function m(){u?u.classList.add("is-hidden"):console.warn("Element is apsent")}const p=document.querySelector(".form"),y=document.querySelector(".gallery");document.querySelector(".input");const v=document.querySelector(".load-more");let a=1;const q=40;let c="";p&&p.addEventListener("submit",async t=>{if(t.preventDefault(),f(),c=t.currentTarget.elements["search-text"].value.trim(),!c){i.warning({title:"Warning",message:"Будь ласка, введіть значення!",position:"topRight"});return}f(),b(),a=1,m(),y.innerHTML="",v.style.display="none";try{const e=await g(c,a);if(!e.hits||e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(e.hits),i.success({title:"Success",message:`Ми знайшли ${e.hits.length} зображень!`,position:"topRight"}),y.innerHTML=createGalleryMarkup(e.hits),e.totalHits>q&&(S(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){i.error({title:"Error",message:"Сталася помилка під час завантаження. Спробуйте пізніше!",position:"topRight"}),console.error("Fetch error:",e)}finally{w(),t.target.reset()}});v.addEventListener("click",async()=>{a+=1,m(),b();try{const t=await g(c,a);L(t.hits),R();const e=Math.ceil(t.totalHits/q);a>=e?(i.info({message:"We're sorry, but you've reached the end of search results."}),m()):S()}catch(t){i.error({message:"Сталася помилка під час завантаження. Спробуйте ще раз."}),console.error(t)}finally{w()}});async function R(){const t=document.querySelectorAll(".gallery a");if(t.length>0){const e=t[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
