/* empty css                      */import{a as E,S as $,i}from"./assets/vendor-CIF6YjI2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const P="56203683-dd16d7902fd33711f42dee53b",B="https://pixabay.com/api/";let M="";const R=15;async function h(t,e){t!==M&&(e=1);try{return(await E.get(B,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:R}})).data}catch(s){throw console.error("Error",s),s}}const x=new $(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");function L(t){m();const e=t.map(({webformatURL:s,largeImageURL:l,tags:r,likes:o,views:n,comments:q,downloads:v})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${s}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${o}</p>
            <p class="info-item"><b>Views</b> ${n}</p>
            <p class="info-item"><b>Comments</b> ${q}</p>
            <p class="info-item"><b>Downloads</b> ${v}</p>
          </div>
        </li>
      `).join("");y.insertAdjacentHTML("beforeend",e),x.refresh()}function m(){y.innerHTML=""}function b(){d&&d.classList.remove("is-hidden")}function w(){d?d.classList.add("is-hidden"):console.warn("Element is apsent")}function S(){u&&u.classList.remove("is-hidden")}function f(){u?u.classList.add("is-hidden"):console.warn("Element is apsent")}const g=document.querySelector(".form");document.querySelector(".gallery");document.querySelector(".input");const H=document.querySelector(".load-more");let a=1;const p=40;let c="";g&&g.addEventListener("submit",async t=>{if(t.preventDefault(),m(),c=t.currentTarget.elements["search-text"].value.trim(),!c){i.warning({title:"Warning",message:"Будь ласка, введіть значення!",position:"topRight"});return}m(),b(),a=1,f();try{const e=await h(c,a);if(!e.hits||e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(e.hits),i.success({title:"Success",message:`Ми знайшли ${e.hits.length} зображень!`,position:"topRight"}),e.totalHits<=p&&i.info({title:"Увага",message:"Ви переглянули всі доступні зображення за вашим запитом.",position:"topRight",timeout:4e3}),e.totalHits>p&&S()}catch(e){i.error({title:"Error",message:"Сталася помилка під час завантаження. Спробуйте пізніше!",position:"topRight"}),console.error("Fetch error:",e)}finally{w(),t.target.reset()}});H.addEventListener("click",async()=>{a+=1,f(),b();try{const t=await h(c,a);L(t.hits),O();const e=Math.ceil(t.totalHits/p);a>=e?(i.info({message:"We're sorry, but you've reached the end of search results."}),f()):S()}catch(t){i.error({message:"Сталася помилка під час завантаження. Спробуйте ще раз."}),console.error(t)}finally{w()}});async function O(){const t=document.querySelectorAll(".gallery a");if(t.length>0){const e=t[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
